# General settings.
spk: "meian"

# exp tag(for managing experiments)
tag:

sample_rate: 16000

# 1) none 2) tqdm
# NOTE: Jupyterノートブックからrun.shを実行する場合は、none推奨
tqdm: tqdm

# NOTE: benchmarkをtrueにすると、高速化が期待できる分、より多くの
# GPUリソースを必要とする場合があります
cudnn_benchmark: true
cudnn_deterministic: false

###########################################################
#                DATA PREPARATION SETTING                 #
###########################################################

# PLEASE CHANGE THE PATH BASED ON YOUR ENVIRONMENT
db_root: "downloads/css10/ja"
lab_root: "downloads/css10-lab/ja"

n_jobs: 4

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################

# HTS-style question used for extracting linguistic contexts
qst_path: "../../../recipes/common/qst1.hed"

###########################################################
#                TRAINING SETTING                         #
###########################################################

duration_model: duration_dnn
acoustic_model: acoustic_dnn_sr24k

# その他詳細なパラメータは、conf/train_dnntts を確認してください
# エポック数を小さくすると、学習は早く終了します。
dnntts_train_nepochs: 30
# バッチサイズを小さくすると、GPUメモリ使用量が小さく済みます。
dnntts_data_batch_size: 32

###########################################################
#                SYNTHESIS SETTING                        #
###########################################################

# リストの逆順で発話を処理する
reverse: false

# 生成する発話の数
# -1 の場合、評価の発話をすべて処理する
# 音声生成にかかる時間を短縮する場合、小さな値（5など）に設定してください
num_eval_utts: -1

# latest.pth or best_loss.pth
duration_eval_checkpoint: latest.pth
acoustic_eval_checkpoint: latest.pth

# 生成された特徴量に対してポストフィルタを適用するかどうか
post_filter: true